apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # You must replace this email address with your own.
    # Let's Encrypt will use this to contact you about expiring
    # certificates, and issues related to your account.
    email: hiroki11hanada@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: letsencrypt-prod
    # Add a single challenge solver, HTTP01 using nginx
    solvers:
    - dns01:
        route53:
          region: ap-northeast-1
          hostedZoneID:***REMOVED***
          accessKeyID:***REMOVED***
          secretAccessKeySecretRef:
            name: route53-secret
            key: secret-access-key
